<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CPX-A9PR29BJFIU" name="runners.testRunner1" tests="1" failures="0" timestamp="26 Jun 2018 21:41:44 GMT" time="19.439" errors="1">
  <testcase name="feature" time="19.439" classname="runners.testRunner1">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [AUTHENTICATION] but found [AUTHENTICATIONN]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:
	expected [AUTHENTICATION] but found [AUTHENTICATIONN]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: The following asserts failed:
	expected [AUTHENTICATION] but found [AUTHENTICATIONN]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at stepDefinitions.Feature01.signOut(Feature01.java:165)
	at âœ½.And I click on SignOut button(Feature02.feature:14)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runners.testRunner1 -->
